### ISSUE TITLE
Demo Scene doesn't contain any Logic (except the FPS counter)

### ISSUE THREAD

**Issue by JimWest** [adrenak/UniCV#1]
Seems like you missed to add your "WebCamTextureCVBehaviour" script to any GameObject in the Scene, so currently running the Scene does nothing except showing 2 empty Qudas and the current FPS.

**Comment by adrenak** [comment]
Added the WebCamTextureCVBehaviour component on the Video Processor gameobject. Confirmed to be running on my PC.
